language: julia
os:
- linux
- osx
julia:
- 0.4
- 0.5
- nightly
notifications:
  email: false
  slack:
    secure: isuFiNt773RPNqSj78OcGuozuG9/QsAe+mEZZOjmlSrdWYBGU7v0wi6UZ/XJJF3H5HQrtEUrmU7I4ApiiixeHfw3FiR9EtWmuYn8P3y2b95C4Y34JGZb7ot6B27OA84+FIASriGkdJEdlXq5pah1mOcmgzs46jCl9Q5vFFJx1P+LN7fzBF2FWQ+iKnEv3FCrl+X8yxmABNM8Jp2OoqD6rMzRkhdMz8fHM96HmXRT5PHR86Ky3eqnyvQjXA+k6dOvBFDY7MbqamwArfEe8vAeRozuyjhS6OQNeC0u4gcaylxQWFOWOYbUfGqbM03UfW+jAB1NqThhyxIMzWJoFSzFLobni4C9pQUd4fxvxkBWrPBB39EEAq1zC10zsVS18PKtSEz+dBnI4p9255HqAZLZXgtinfPbXBX27DmHNW6crotEHa4x4th8+i6NozTQfOQGPQUB5lxMe8HX0J+VKTh6ok03COIrANbqhy0bIXOu7zAttuWanQJF0xx/n+AJvmrZB9676fTTFdBQOSQdTBnlQqhk6KlmzCSJJZ2aglXdtxWNn0YvlTzCA80Hw4Em7a6Z9KEpOtKN1Gm9Bc45uT938eLGxv+TPRfNxXgmxzlJZtmEpEfyyJSnY9+dvsRTWUIIRGj3ecbHtIv5n0tiULUZA2sekq2qWNSSMkEAijT2ScI=
env:
  secure: mO7kiWHPrD7P8ON1QvkNbsFZVZVtgWee+by9NmxbdBhNuub/VGMakWo1AdZvlBtmAXQfu40zXqWq/1mY1UJqy7dkTtPyokINfxzQSFZsypom2glf4WAdKSBuOb31F8SOS0QehuVrZKKCcRofzv139ETKjrK3TFnPVx5I3dcSEBL5wwfWjOSbsjowsjUnLLLMZNeMcu3O89GhpQITbFofDKRPFwXoEhc+lbf0dGcO9V2sNFQK3RG/XrvZDo4auWHPFUX52yi8Kk7Iol9kuiTCHKaZWevLiw+LLKG35TpeHRp+CPQsEB5yvw7Sg/5yoBNkw0rlj0x1+dJ/yqba3Yt8EOMMG81it9/tJuRC3lEuvAiQhjalI2tXqV5MdmGe/9uVzT47fwz0PHP3jYbOVhhx4KWJTxgkT92CAaQuO4xYcCnAyMi7j+rIuYA70nO4cnjrbnQQ3XZwEmyufL5xusMIwNsEKQbIdRF+kPfqva722wM96YxwFydW8N2njfl1ZNNQpqJ7+TQklKKWl1aAoVVGFLP5uxCpnblbhY8I7sixmN4g7e4/OYa6LUEvMpp7YRHXxWzq3rwFfksrRaNC3omeGBkTDMmxW8RCqIy7JK5dnVPouA84F1CkYLogOtfpNahFXVVeDrP6Fo3VHgUEATqCqo3lDDRM4+C9oY+sXitDIi4=
